/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoescuelaClases;

import BBDD.Conexion;
import Clases.Persona;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
       
        initComponents();
        configuracion();
        
    }
    public void configuracion(){
     con= new Conexion();
     jComboBoxmatricula.removeAllItems();
        ArrayList<String> vMatriculas = con.mostrarDatosTablaporCaposconcretos("vehiculo","matricula");
        jComboBoxmatricula.addItem("Matriculas");
        for (int i = 0; i < vMatriculas.size(); i++) {
            jComboBoxmatricula.addItem(vMatriculas.get(i));
        }
        jComboBoxdniProfesor.removeAllItems();
        ArrayList<String> vDniProfesor = con.mostrarDatosTablaporCaposconcretosmasTipo("persona","dni","profesor");
        jComboBoxdniProfesor.addItem("Profesores");
        for (int i = 0; i < vDniProfesor.size(); i++) {
            jComboBoxdniProfesor.addItem(vDniProfesor.get(i));
        }
        jComboBoxidalumno.removeAllItems();
         jComboBoxidalumno.addItem("Alumnos");
        ArrayList<String> vIDAlumno = con.mostrarDatosTablaporCaposconcretosmasTipo("persona","id","alumno");
        for (int i = 0; i < vIDAlumno.size(); i++) {
            jComboBoxidalumno.addItem(vIDAlumno.get(i));
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupadmin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonañadircoche = new javax.swing.JButton();
        jButtoneliminarcoche = new javax.swing.JButton();
        jLabelmatricula = new javax.swing.JLabel();
        jTextFieldmatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldmodelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxmatricula = new javax.swing.JComboBox<>();
        jTextFieldpotencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldtipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFielddni = new javax.swing.JTextField();
        jButtonañadirprofesor = new javax.swing.JButton();
        jButtoneliminarprofesor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldnombreprofesor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldpremisosprofesor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldnacimientoProfesor = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldtlfprofesor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxdniProfesor = new javax.swing.JComboBox<>();
        jRadioButtontrueprofesor = new javax.swing.JRadioButton();
        jRadioButtonfalseprofesor = new javax.swing.JRadioButton();
        jTextFieldcontraseñaprofesor = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldcorreoprofesor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonañadiralumno = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldtlfalumno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldnombrealumno = new javax.swing.JTextField();
        jTextFieldcorreoalumno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFielddnialumno = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldpermisosalumno = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldnacimientoalumno = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldidalumno = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBoxidalumno = new javax.swing.JComboBox<>();
        jButtoneliminaralumno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonañadiralumno1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Admistrar Vehiculos"));

        jButtonañadircoche.setText("Añadir");
        jButtonañadircoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonañadircocheActionPerformed(evt);
            }
        });

        jButtoneliminarcoche.setText("Eliminar");
        jButtoneliminarcoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarcocheActionPerformed(evt);
            }
        });

        jLabelmatricula.setText("Matricula:");

        jTextFieldmatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldmatriculaFocusLost(evt);
            }
        });

        jLabel3.setText("Modelo:");

        jTextFieldmodelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldmodeloFocusLost(evt);
            }
        });
        jTextFieldmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmodeloActionPerformed(evt);
            }
        });

        jLabel4.setText("Matricula:");

        jTextFieldpotencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldpotenciaFocusLost(evt);
            }
        });

        jLabel5.setText("Potencia:");

        jTextFieldtipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldtipoFocusLost(evt);
            }
        });

        jLabel6.setText("Tipo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtoneliminarcoche)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonañadircoche, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonañadircoche)
                    .addComponent(jTextFieldpotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoneliminarcoche)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Profesores"));

        jButtonañadirprofesor.setText("Añadir");
        jButtonañadirprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonañadirprofesorActionPerformed(evt);
            }
        });

        jButtoneliminarprofesor.setText("Eliminar");
        jButtoneliminarprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminarprofesorActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre:");

        jTextFieldnombreprofesor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnombreprofesorFocusLost(evt);
            }
        });

        jLabel10.setText("DNI:");

        jLabel16.setText("Permisos:");

        jTextFieldpremisosprofesor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldpremisosprofesorFocusLost(evt);
            }
        });

        jLabel17.setText("Fecha Nacimiento:");

        jTextFieldnacimientoProfesor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnacimientoProfesorFocusLost(evt);
            }
        });

        jLabel18.setText("Tlf:");

        jLabel19.setText("Admin:");

        jLabel23.setText("DNI:");

        buttonGroupadmin.add(jRadioButtontrueprofesor);
        jRadioButtontrueprofesor.setText("True");

        buttonGroupadmin.add(jRadioButtonfalseprofesor);
        jRadioButtonfalseprofesor.setSelected(true);
        jRadioButtonfalseprofesor.setText("False");
        jRadioButtonfalseprofesor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonfalseprofesor.setFocusPainted(false);

        jTextFieldcontraseñaprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcontraseñaprofesorActionPerformed(evt);
            }
        });

        jLabel39.setText("Contraseña:");

        jLabel28.setText("Correo:");

        jTextFieldcorreoprofesor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldcorreoprofesorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldnombreprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldnacimientoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldpremisosprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtlfprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcorreoprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxdniProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoneliminarprofesor)))
                .addGap(10, 10, 10)
                .addComponent(jTextFieldcontraseñaprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtontrueprofesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonfalseprofesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonañadirprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtontrueprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonañadirprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButtonfalseprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldcontraseñaprofesor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldcorreoprofesor)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldnacimientoProfesor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldnombreprofesor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFielddni, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldpremisosprofesor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldtlfprofesor, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxdniProfesor)
                        .addComponent(jButtoneliminarprofesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Alumnos"));

        jButtonañadiralumno.setText("Añadir");
        jButtonañadiralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonañadiralumnoActionPerformed(evt);
            }
        });

        jLabel26.setText("Tlf:");

        jLabel11.setText("Nombre:");

        jLabel27.setText("Correo:");

        jTextFieldnombrealumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldnombrealumnoFocusLost(evt);
            }
        });

        jTextFieldcorreoalumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldcorreoalumnoFocusLost(evt);
            }
        });

        jLabel13.setText("DNI:");

        jLabel33.setText("Permisos:");

        jLabel35.setText("Fecha Nacimiento:");

        jTextFieldnacimientoalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnacimientoalumnoActionPerformed(evt);
            }
        });

        jLabel36.setText("ID:");

        jTextFieldidalumno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldidalumnoFocusLost(evt);
            }
        });

        jLabel37.setText("ID:");

        jButtoneliminaralumno.setText("Eliminar");
        jButtoneliminaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneliminaralumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtoneliminaralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldnombrealumno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielddnialumno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldnacimientoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldpermisosalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtlfalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcorreoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonañadiralumno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldnacimientoalumno)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldpermisosalumno)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldidalumno)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldtlfalumno, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldcorreoalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFielddnialumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldnombrealumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonañadiralumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxidalumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jButtoneliminaralumno))
                .addContainerGap())
        );

        jLabel2.setText("Admin");

        jButtonañadiralumno1.setText("Desconectar");
        jButtonañadiralumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonañadiralumno1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(518, 518, 518)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonañadiralumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonañadiralumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoneliminarcocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarcocheActionPerformed
        String matricula=jComboBoxmatricula.getSelectedItem().toString();
        if(con.eliminar("vehiculo","matricula",matricula)){
             configuracion();
        }
       
    }//GEN-LAST:event_jButtoneliminarcocheActionPerformed

    private void jButtoneliminarprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminarprofesorActionPerformed
       String dniP=jComboBoxdniProfesor.getSelectedItem().toString();
        if(con.eliminar("persona","dni",dniP)){
             configuracion();
        }
    }//GEN-LAST:event_jButtoneliminarprofesorActionPerformed

    private void jButtoneliminaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneliminaralumnoActionPerformed
        String idA=jComboBoxidalumno.getSelectedItem().toString();
        if(con.eliminar("persona","id",idA)){
             configuracion();
        }
    }//GEN-LAST:event_jButtoneliminaralumnoActionPerformed

    private void jButtonañadircocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonañadircocheActionPerformed
        if(con.insertarDatosVehiculo(jTextFieldmatricula.getText(), jTextFieldmodelo.getText(), Integer.valueOf(jTextFieldpotencia.getText()), jTextFieldtipo.getText())){
            configuracion();
            JOptionPane.showMessageDialog(this, "Vehiculo Insertado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "Fallo al insertar un vehiculo");
        }
    }//GEN-LAST:event_jButtonañadircocheActionPerformed

    private void jButtonañadiralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonañadiralumnoActionPerformed
        if(con.insertarDatosPersona(jTextFieldnombrealumno.getText(), jTextFielddnialumno.getText(), jTextFieldnacimientoalumno.getText(), jTextFieldpermisosalumno.getText(),Integer.valueOf(jTextFieldtlfalumno.getText()) , "Alumno", jTextFieldcorreoalumno.getText(), Integer.valueOf(jTextFieldidalumno.getText()), false,"1")){
            configuracion(); 
            JOptionPane.showMessageDialog(this, "Alumno Insertado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "Fallo al insertar un Alumno");
        }
    }//GEN-LAST:event_jButtonañadiralumnoActionPerformed

    private void jTextFieldcontraseñaprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcontraseñaprofesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcontraseñaprofesorActionPerformed

    private void jTextFieldnacimientoalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnacimientoalumnoActionPerformed
        Pattern p = Pattern.compile("\\d{4}/\\d{2}/\\d{2}");
        Matcher m = p.matcher(jTextFieldnacimientoalumno.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce una fecha corecta aaaa/mm/dd");
            jTextFieldnacimientoalumno.setText("");
        }
    }//GEN-LAST:event_jTextFieldnacimientoalumnoActionPerformed

    private void jButtonañadirprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonañadirprofesorActionPerformed
        boolean bandera;
        if(jRadioButtontrueprofesor.isEnabled()){
            bandera = true;
        }else{
            bandera = false;
        }
        if(con.insertarDatosPersona(jTextFieldnombreprofesor.getText(), jTextFielddni.getText(), jTextFieldnacimientoProfesor.getText(), jTextFieldpremisosprofesor.getText(),Integer.valueOf(jTextFieldtlfprofesor.getText()), "Profesor", jTextFieldcorreoprofesor.getText(), 0, bandera, jTextFieldcontraseñaprofesor.getText())){
            configuracion(); JOptionPane.showMessageDialog(this, "profesor Insertado con exito");
        }else{
            JOptionPane.showMessageDialog(this, "Fallo al insertar un profesor");
        }
    }//GEN-LAST:event_jButtonañadirprofesorActionPerformed

    private void jButtonañadiralumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonañadiralumno1ActionPerformed
        Login ventan = new Login();
        ventan.setLocationRelativeTo(this);
        ventan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonañadiralumno1ActionPerformed

    private void jTextFieldmatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmatriculaFocusLost
        Pattern p = Pattern.compile("[A - Z a -z 0 - 9]*");
        Matcher m = p.matcher(jTextFieldmatricula.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce una matricual corecta");
            jTextFieldmatricula.setText("");
        }
    }//GEN-LAST:event_jTextFieldmatriculaFocusLost

    private void jTextFieldmodeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldmodeloFocusLost
          Pattern p = Pattern.compile("[A - Z a -z 0 - 9]*");
        Matcher m = p.matcher(jTextFieldmodelo.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce un modelo corecta");
            jTextFieldmodelo.setText("");
        }
    }//GEN-LAST:event_jTextFieldmodeloFocusLost

    private void jTextFieldnombreprofesorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnombreprofesorFocusLost
          Pattern p = Pattern.compile("[A - Z a -z]*");
        Matcher m = p.matcher(jTextFieldnombreprofesor.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce un nombre corecta");
            jTextFieldnombreprofesor.setText("");
        }
    }//GEN-LAST:event_jTextFieldnombreprofesorFocusLost

    private void jTextFieldmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmodeloActionPerformed

    private void jTextFieldpotenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldpotenciaFocusLost
         Pattern p = Pattern.compile("[0-9]*");
        Matcher m = p.matcher(jTextFieldpotencia.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce la potencia KW corecta");
            jTextFieldpotencia.setText("");
        }
    }//GEN-LAST:event_jTextFieldpotenciaFocusLost

    private void jTextFieldtipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldtipoFocusLost
       Pattern p = Pattern.compile("[A - Z a -z 0 - 9]*");
        Matcher m = p.matcher(jTextFieldtipo.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce un tipo corecta");
            jTextFieldtipo.setText("");
        }
    }//GEN-LAST:event_jTextFieldtipoFocusLost

    private void jTextFieldnacimientoProfesorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnacimientoProfesorFocusLost
        Pattern p = Pattern.compile("\\d{4}/\\d{2}/\\d{2}");
        Matcher m = p.matcher(jTextFieldnacimientoProfesor.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce una fecha corecta aaaa/mm/dd");
            jTextFieldnacimientoProfesor.setText("");
        }
    }//GEN-LAST:event_jTextFieldnacimientoProfesorFocusLost

    private void jTextFieldpremisosprofesorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldpremisosprofesorFocusLost
        Pattern p = Pattern.compile("[A - Z a -z 0 - 9]*");
        Matcher m = p.matcher(jTextFieldpremisosprofesor.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce los permisos corectamente");
            jTextFieldpremisosprofesor.setText("");
        }
    }//GEN-LAST:event_jTextFieldpremisosprofesorFocusLost

    private void jTextFieldcorreoprofesorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldcorreoprofesorFocusLost
        Pattern p = Pattern.compile("[A-Z a-z 0-9]+@[A-Z a-z 0-9]+\\.[A-Z a-z]{2,3}");
        Matcher m= p.matcher(jTextFieldcorreoprofesor.getText());
        if(!m.matches()){
            JOptionPane.showMessageDialog(this, "Introduce un correro valido");
            jTextFieldcorreoprofesor.setText("");
        }
    }//GEN-LAST:event_jTextFieldcorreoprofesorFocusLost

    private void jTextFieldnombrealumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldnombrealumnoFocusLost
         Pattern p = Pattern.compile("[A - Z a -z]*");
        Matcher m = p.matcher(jTextFieldnombrealumno.getText());
        if(!(m.matches())){
            JOptionPane.showMessageDialog(this, "Introduce un nombre corecta");
            jTextFieldnombrealumno.setText("");
        }
    }//GEN-LAST:event_jTextFieldnombrealumnoFocusLost

    private void jTextFieldcorreoalumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldcorreoalumnoFocusLost
        Pattern p = Pattern.compile("[A-Z a-z 0-9]+@[A-Z a-z 0-9]+\\.[A-Z a-z]{2,3}");
        Matcher m= p.matcher(jTextFieldcorreoalumno.getText());
        if(!m.matches()){
            JOptionPane.showMessageDialog(this, "Introduce un correro valido");
            jTextFieldcorreoalumno.setText("");
        }
    }//GEN-LAST:event_jTextFieldcorreoalumnoFocusLost

    private void jTextFieldidalumnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldidalumnoFocusLost
        if(con.comprobarid(jTextFieldidalumno.getText())){
            JOptionPane.showMessageDialog(this, "Introduce un id no repetido ");
            jTextFieldidalumno.setText("");
        }
    }//GEN-LAST:event_jTextFieldidalumnoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }
    private Conexion con;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupadmin;
    private javax.swing.JButton jButtonañadiralumno;
    private javax.swing.JButton jButtonañadiralumno1;
    private javax.swing.JButton jButtonañadircoche;
    private javax.swing.JButton jButtonañadirprofesor;
    private javax.swing.JButton jButtoneliminaralumno;
    private javax.swing.JButton jButtoneliminarcoche;
    private javax.swing.JButton jButtoneliminarprofesor;
    private javax.swing.JComboBox<String> jComboBoxdniProfesor;
    private javax.swing.JComboBox<String> jComboBoxidalumno;
    private javax.swing.JComboBox<String> jComboBoxmatricula;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelmatricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonfalseprofesor;
    private javax.swing.JRadioButton jRadioButtontrueprofesor;
    private javax.swing.JTextField jTextFieldcontraseñaprofesor;
    private javax.swing.JTextField jTextFieldcorreoalumno;
    private javax.swing.JTextField jTextFieldcorreoprofesor;
    private javax.swing.JTextField jTextFielddni;
    private javax.swing.JTextField jTextFielddnialumno;
    private javax.swing.JTextField jTextFieldidalumno;
    private javax.swing.JTextField jTextFieldmatricula;
    private javax.swing.JTextField jTextFieldmodelo;
    private javax.swing.JTextField jTextFieldnacimientoProfesor;
    private javax.swing.JTextField jTextFieldnacimientoalumno;
    private javax.swing.JTextField jTextFieldnombrealumno;
    private javax.swing.JTextField jTextFieldnombreprofesor;
    private javax.swing.JTextField jTextFieldpermisosalumno;
    private javax.swing.JTextField jTextFieldpotencia;
    private javax.swing.JTextField jTextFieldpremisosprofesor;
    private javax.swing.JTextField jTextFieldtipo;
    private javax.swing.JTextField jTextFieldtlfalumno;
    private javax.swing.JTextField jTextFieldtlfprofesor;
    // End of variables declaration//GEN-END:variables
}
